jobs:
- job: Plan
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: |
      terraform init
      terraform plan
- job: Apply
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: |
      terraform init
      terraform apply
